package ren.liushuang.mytool.serverapi.model.equip;

import java.util.ArrayList;

import lombok.Data;

@Data
public class Equip {

    private float qixue;
    private float max_expt_fashu;
    private float lingli;
    private String fair_show_end_time_left;
    private float all_damage;
    private float speed;
    private float max_expt_fangyu;
    private String appointed_roleid = null;
    private float addon_minjie;
    private String server_name;
    ArrayList< Object > highlights = new ArrayList < Object > ();
    private float init_hp;
    private float init_defense;
    private float bb_expt_gongji;
    private float equip_count;
    private float min_buyer_level;
    private String area_name;
    private float expt_kangfa;
    private float max_expt_gongji;
    private float magic_damage;
    private float minjie;
    private float suit_skill;
    private String desc;
    private float school;
    private float zongshang;
    private float level;
    private float fangyu;
    private String equip_name;
    private float magic_defense;
    private String server_sn;
    private String selling_time;
    private float xiang_qian_level;
    private String equip_level_desc;
    private float mingzhong;
    private float init_wakan;
    private float is_collect;
    private String equip_face_img;
    private String create_time;
    private float equipid;
    private float anti_fengyin;
    private float bb_expt_fashu;
    private float bb_expt_kangfa;
    private float init_damage;
    private float shanghai;
    private String seller_nickname;
    private float expt_gongji;
    private float expt_fangyu;
    private float max_expt_kangfa;
    private float addon_total;
    private float mofa;
    private float jinglian_level;
    private float price_int;
    private float gem_level;
    private float addon_skill_chance;
    private String time_left;
    private float storage_type;
    private float expt_fashu;
    private float collect_num;
    private float server_id;
    private float score;
    private float bb_expt_fangyu;
    private float addon_effect_chance;
    private float kindid;
    private float addon_naili;
    private float hp;
    private String unit_price_desc;
    private float init_dex;
    private String game_ordersn;
    private float fengyin;
    private float defense;
    private String eid;
    private float addon_fali;
    private float addon_status;
    private String tag;
    private float addon_lingli;
    private float addon_tizhi;
    private float init_damage_raw;
    private float damage;
    private float suit_effect;
    private float special_skill;
    private float equip_level;
    private float addon_liliang;
    private float status;
    private String equip_type;
    private String price;
    private String other_info;
    private String equip_type_desc;
    private String expire_time;
    private float serverid;
    private float icon;
    private String special_effect;
    private String gem_value ;
    private String seller_roleid;
}
